version: '3.7'

services:
  konga:
    image: pantsel/konga
    container_name: konga
    ports:
      - 0.0.0.0:1337:1337
    environment:
      DB_ADAPTER: postgres
      DB_DATABASE: konga
      DB_HOST: 192.168.40.91
      NODE_ENV: production
      DB_USER: root
      DB_PASSWORD: 123456
      TOKEN_SECRET: thisistest