version: '3.7'

services:
  kong-migration:
    image: kong:2.1.0-alpine
    container_name: kong-migration
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: 192.168.40.91
      KONG_PG_USER: root
      KONG_PG_PASSWORD: 123456
    command: kong migrations bootstrap